language: python
matrix:
  include:
  - env: TARGET="linux-python36"
    os: linux
    dist: trusty
    sudo: required
    group: edge
    python: 3.6
  - os: osx
    language: generic
    python: 3.6
cache: pip
install:
- pip install -r requirements.txt
- pip install coverage
script:
- if test ${TARGET} = "linux-python36"; then coverage run --source=plasoscaffolder ./run_tests_for_coverage.py test; else ./run_tests.py; fi
after_success:
- if test ${TARGET} = "linux-python36"; then curl -o codecov.sh -s https://codecov.io/bash && /bin/bash ./codecov.sh; fi
