language: python
matrix:
  include:
  - env: TARGET="linux-python36"
    os: linux
    dist: trusty
    sudo: required
    group: edge
    python: 3.6
  - env: TARGET="macosx-python36"
    os: osx
    language: generic
    python: 3.6
  allow_failures:
  - env: TARGET="macosx-python36"
cache: pip
install:
- pip install -r requirements.txt
- pip install coverage
script:
- coverage run --source=l2tscaffolder ./run_tests.py test
after_success:
- curl -o codecov.sh -s https://codecov.io/bash && /bin/bash ./codecov.sh
